// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5vxguZc7DFqrcHHOel3HGyMlEUy40QQ',
    appId: '1:248835344678:web:1a941b1e238f08bece19e7',
    messagingSenderId: '248835344678',
    projectId: 'locate-it-e063c',
    authDomain: 'locate-it-e063c.firebaseapp.com',
    databaseURL: 'https://locate-it-e063c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locate-it-e063c.appspot.com',
    measurementId: 'G-Y91TPRHEZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1YZ6jYY-xsbj0A_KvCOM0vh0RUVNyueE',
    appId: '1:248835344678:android:0b474adc0acae2e6ce19e7',
    messagingSenderId: '248835344678',
    projectId: 'locate-it-e063c',
    databaseURL: 'https://locate-it-e063c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locate-it-e063c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRNwaI-dx1Pc9nKuoZsq9FxOqjg8Rwmg',
    appId: '1:248835344678:ios:d0e1b7622815ca48ce19e7',
    messagingSenderId: '248835344678',
    projectId: 'locate-it-e063c',
    databaseURL: 'https://locate-it-e063c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locate-it-e063c.appspot.com',
    iosClientId: '248835344678-8mv11pb26ojp6m4p858hdup54ubihdcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.locateItUser1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRNwaI-dx1Pc9nKuoZsq9FxOqjg8Rwmg',
    appId: '1:248835344678:ios:d0e1b7622815ca48ce19e7',
    messagingSenderId: '248835344678',
    projectId: 'locate-it-e063c',
    databaseURL: 'https://locate-it-e063c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locate-it-e063c.appspot.com',
    iosClientId: '248835344678-8mv11pb26ojp6m4p858hdup54ubihdcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.locateItUser1',
  );
}
